version: "3.8"

services:
  # Firebase Firestore
  # database:
  #   image: goatlab/firebase-emulator:latest
  #   ports:
  #     - 8080:8080
  #     - 4000:4000
  #   volumes:
  #     - ./firebaseSeed:/app/firebaseSeed
  #   command: firebase emulators:start --project highlevel-68ed3 --only firestore --import='./firebaseSeed' --export-on-exit

  # NestJS Services
  services:
    build:
      dockerfile: Dockerfile
      context: ./services
    ports:
      - 3000:3000
    # links:
    #   - database
  
  # React Webapp
  webapp:
    build:
      dockerfile: Dockerfile
      context: ./webapp
    environment:
     REACT_APP_SERVICE_URL: 'http://localhost:3000'
    ports:
      - 4200:80
    links:
      - services